# Họ và tên: Nguyễn Vũ Dương
# Mã số sinh viên: 20520465

## Load library

In [111]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

##Load dữ liệu từ file CSV

In [112]:
dataset = pd.read_csv("./50_Startups.csv")
dataset.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [113]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [114]:
print(X.shape)
print(y.shape)

(50, 4)
(50,)


In [115]:
y = y.reshape(len(y), 1)

##Chuyển đổi các đặc trưng dạng phân loại sang dạng số sử dụng OneHotEncoder

In [116]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X_onehot = np.array(ct.fit_transform(X))
print(X_onehot)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

###Chia tập dữ liệu thành 2 phần train và test theo tỉ lệ 8:2

In [117]:
X_train, X_test, y_train, y_test = train_test_split(X_onehot, y, test_size=0.2, random_state=0)

###Tạo mô hình Linear Regression với sklearn và huấn luyện trên dữ liệu train

In [118]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

###Sử dụng mô hình đã huấn luyện để dự đoán trên tập test

In [119]:
y_pred = lr.predict(X_test)
print(y_pred)
print(y_test)

[[103015.20159795]
 [132582.27760816]
 [132447.73845175]
 [ 71976.09851258]
 [178537.48221057]
 [116161.24230167]
 [ 67851.69209676]
 [ 98791.73374687]
 [113969.43533014]
 [167921.06569552]]
[[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]]


###Đánh giá hiệu quả của mô hình trên cả 2 tập train và test

In [120]:
mse_train = mean_squared_error(y_train, lr.predict(X_train))
print('Mean square error on train:', mse_train)
mse_test = mean_squared_error(y_test, y_pred)
print('Mean square error on test:', mse_test)

Mean square error on train: 81571001.80077367
Mean square error on test: 83502864.03256194


In [121]:
rms_train = mean_squared_error(y_train, lr.predict(X_train), squared=False)
rms_test = mean_squared_error(y_test, y_pred, squared=False)
print('Root mean square error on train:', rms_train)
print('Root mean square error on test:', rms_test)


Root mean square error on train: 9031.666612578969
Root mean square error on test: 9137.9901527941


In [122]:
mape_train=mean_absolute_percentage_error(y_train, lr.predict(X_train))
mape_test=mean_absolute_percentage_error(y_test, y_pred)
print('Mean absolute percentage error on train:',mape_train)
print('Mean absolute percentage error on test:',mape_test)

Mean absolute percentage error on train: 0.11643543574240908
Mean absolute percentage error on test: 0.06449754085358202


## Chuyển đổi các đặc trưng dạng phân loại sang dạng số sử dụng trọng số 

In [125]:
labelencoder = LabelEncoder()
X_label = X.copy()
X_label[:,-1] = labelencoder.fit_transform(X_label[:,-1])
print(X_label)

[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 1]
 [131876.9 99814.71 362861.36 2]
 [134615.46 147198.87 127716.82 0]
 [130298.13 145530.06 323876.68 1]
 [120542.52 148718.95 311613.29 2]
 [123334.88 108679.17 304981.62 0]
 [101913.08 110594.11 229160.95 1]
 [100671.96 91790.61 249744.55 0]
 [93863.75 127320.38 249839.44 1]
 [91992.39 135495.07 252664.93 0]
 [119943.24 156547.42 256512.92 1]
 [114523.61 122616.84 261776.23 2]
 [78013.11 121597.55 264346.06 0]
 [94657.16 145077.58 282574.31 2]
 [91749.16 114175.79 294919.57 1]
 [86419.7 153514.11 0.0 2]
 [76253.86 113867.3 298664.47 0]
 [78389.47 153773.43 299737.29 2]
 [73994.56 122782.75 303319.26 1]
 [67532.53 105751.03 304768.73 1]
 [77044.01 99281.34 140574.81 2]
 [64664.71 139553.16 137962.62 0]
 [75328.87 144135.98 134050.07 1]
 [72107.6 127864.55 353183.81 2]
 [66051.52 182645.56 118148.2 1]
 [65605.48 153032.0

###Chia tập dữ liệu thành 2 phần train và test theo tỉ lệ 8:2

In [126]:
X_train, X_test, y_train, y_test = train_test_split(X_label, y, test_size=0.2, random_state=0)

###Tạo mô hình Linear Regression với sklearn và huấn luyện trên dữ liệu train

In [127]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

###Sử dụng mô hình đã huấn luyện để dự đoán trên tập test

In [128]:
y_pred = lr.predict(X_test)
print(y_pred)
print(y_test)

[[103959.40508021]
 [132398.73236694]
 [133529.03790148]
 [ 72958.28368314]
 [179534.78737166]
 [115533.62584099]
 [ 67476.95847883]
 [ 98504.36199396]
 [114789.16083781]
 [168972.21909945]]
[[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]]


###Đánh giá hiệu quả của mô hình trên cả 2 tập train và test

In [129]:
mse_train = mean_squared_error(y_train, lr.predict(X_train))
print('Mean square error on train:', mse_train)
mse_test = mean_squared_error(y_test, y_pred)
print('Mean square error on test:', mse_test)

Mean square error on train: 81871927.54726207
Mean square error on test: 78413822.17201345


In [130]:
rms_train = mean_squared_error(y_train, lr.predict(X_train), squared=False)
rms_test = mean_squared_error(y_test, y_pred, squared=False)
print('Root mean square error on train:', rms_train)
print('Root mean square error on test:', rms_test)


Root mean square error on train: 9048.310756559042
Root mean square error on test: 8855.157941675205


In [131]:
mape_train=mean_absolute_percentage_error(y_train, lr.predict(X_train))
mape_test=mean_absolute_percentage_error(y_test, y_pred)
print('Mean absolute percentage error on train:',mape_train)
print('Mean absolute percentage error on test:',mape_test)

Mean absolute percentage error on train: 0.11623908137903367
Mean absolute percentage error on test: 0.06344130977384704
